# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BigchainDB Web Socket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BigchainDB Web Socket
pod 'SwiftWebSocket'
pod 'Alamofire', '~> 4.4'

target 'BigchainDB Web SocketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BigchainDB Web SocketUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
